### ISSUE TITLE
Update DNAStackWESClient for new methods to obtain tokens

### ISSUE THREAD

**Issue by ianfore** [ga4gh/fasp-scripts#6]
Was informed that DNAStack are replacing the WES Server we used for 2020 plenary. That server was used by DNAStackWESclient in this repo so the code will need to be updated. One revision will be to the approach to obtain tokens. (Passport? @mbarkley :-)

Creating a ticket now in anticipation of the revised WES server.

**Comment by mbarkley** [comment]
@ianfore thanks for filing this issue. You can assign it to me if you'd like.

**Comment by ianfore** [comment]
Assigned to Max. Please reassign to me when your server and token supplier is available. Unless you want to recode the Python client yourself!
